[theme]
primaryColor = "#2E7D32" # Hijau Kemenag
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F8E9"
textColor = "#212121"
font = "sans serif"
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1dCPVMAk7GZ9OrozXsu9T5WlujsoI6VaDsa7NrmBB3MU/"
